version: '3.9'

services:
  web:
    build: .
    command: sh -c "sleep 5 && gunicorn carbon_tracking.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: carbon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bhavani333$
    ports:
      - "5432:5432"

volumes:
  postgres_data:
