# Generated by Django 5.1.4 on 2025-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='create_account',
            name='last_name',
        ),
        migrations.AddField(
            model_name='create_account',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='create_account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
