# Generated by Django 5.1.4 on 2025-02-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_create_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_account',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='create_account',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
