# Generated by Django 5.1.4 on 2025-02-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_create_account_name_alter_create_account_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_name', models.CharField(max_length=10)),
                ('demo_no', models.IntegerField()),
            ],
        ),
    ]
