# Generated by Django 5.1.4 on 2025-02-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='create_account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
