# Generated by Django 5.1.4 on 2025-06-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_create_account_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
        migrations.RemoveField(
            model_name='create_account',
            name='username',
        ),
    ]
