# Generated by Django 5.1.4 on 2025-07-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electric_type', models.CharField(max_length=50)),
                ('energy_consumed', models.FloatField()),
                ('electricity_factor', models.FloatField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('fuel_consumed', models.FloatField()),
                ('fuel_factor', models.FloatField()),
                ('transport_mode', models.CharField(max_length=50)),
                ('distance_traveled', models.FloatField()),
                ('load_weight', models.FloatField()),
                ('transport_factor', models.FloatField()),
                ('methane_volume', models.FloatField()),
                ('gwp_methane', models.FloatField(default=28)),
                ('land_type', models.CharField(max_length=50)),
                ('area_cleared', models.FloatField()),
                ('carbon_stock_per_hectare', models.FloatField()),
                ('area_rehabilitated', models.FloatField()),
                ('rehab_rate', models.FloatField()),
                ('coal_type', models.CharField(max_length=50)),
                ('coal_produced', models.FloatField()),
                ('coal_emission_factor', models.FloatField()),
                ('carbon_content_fraction', models.FloatField()),
            ],
        ),
    ]
