# Generated by Django 5.1.4 on 2025-07-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_carbondata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbondata',
            name='coal_emission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='electricity_emission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='fuel_emission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='land_cleared_emission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='land_offset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='methane_emission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='total_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='transport_emission',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
