name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Add EC2 IP to known_hosts
        run: |
          ssh-keyscan -H 13.201.255.61 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i key.pem ubuntu@13.201.255.61 "cd ~/Dockerized_Carbon_Tracker && docker-compose down && git pull origin main && docker-compose up -d --build"
